//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NMEA_Parser {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Identifier {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Identifier() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NMEA_Parser.Identifier", typeof(Identifier).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AG.
        /// </summary>
        internal static string AG {
            get {
                return ResourceManager.GetString("AG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AP.
        /// </summary>
        internal static string AP {
            get {
                return ResourceManager.GetString("AP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD.
        /// </summary>
        internal static string CD {
            get {
                return ResourceManager.GetString("CD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CR.
        /// </summary>
        internal static string CR {
            get {
                return ResourceManager.GetString("CR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CS.
        /// </summary>
        internal static string CS {
            get {
                return ResourceManager.GetString("CS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT.
        /// </summary>
        internal static string CT {
            get {
                return ResourceManager.GetString("CT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV.
        /// </summary>
        internal static string CV {
            get {
                return ResourceManager.GetString("CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CX.
        /// </summary>
        internal static string CX {
            get {
                return ResourceManager.GetString("CX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DF.
        /// </summary>
        internal static string DF {
            get {
                return ResourceManager.GetString("DF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DM.
        /// </summary>
        internal static string DM {
            get {
                return ResourceManager.GetString("DM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EC.
        /// </summary>
        internal static string EC {
            get {
                return ResourceManager.GetString("EC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EP.
        /// </summary>
        internal static string EP {
            get {
                return ResourceManager.GetString("EP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER.
        /// </summary>
        internal static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP.
        /// </summary>
        internal static string GP {
            get {
                return ResourceManager.GetString("GP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HC.
        /// </summary>
        internal static string HC {
            get {
                return ResourceManager.GetString("HC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE.
        /// </summary>
        internal static string HE {
            get {
                return ResourceManager.GetString("HE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HN.
        /// </summary>
        internal static string HN {
            get {
                return ResourceManager.GetString("HN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to II.
        /// </summary>
        internal static string II {
            get {
                return ResourceManager.GetString("II", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN.
        /// </summary>
        internal static string IN {
            get {
                return ResourceManager.GetString("IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        internal static string LC {
            get {
                return ResourceManager.GetString("LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string P {
            get {
                return ResourceManager.GetString("P", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RA.
        /// </summary>
        internal static string RA {
            get {
                return ResourceManager.GetString("RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SD.
        /// </summary>
        internal static string SD {
            get {
                return ResourceManager.GetString("SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN.
        /// </summary>
        internal static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        internal static string SS {
            get {
                return ResourceManager.GetString("SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TI.
        /// </summary>
        internal static string TI {
            get {
                return ResourceManager.GetString("TI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VD.
        /// </summary>
        internal static string VD {
            get {
                return ResourceManager.GetString("VD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VW.
        /// </summary>
        internal static string VW {
            get {
                return ResourceManager.GetString("VW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WI.
        /// </summary>
        internal static string WI {
            get {
                return ResourceManager.GetString("WI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YX.
        /// </summary>
        internal static string YX {
            get {
                return ResourceManager.GetString("YX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZA.
        /// </summary>
        internal static string ZA {
            get {
                return ResourceManager.GetString("ZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZC.
        /// </summary>
        internal static string ZC {
            get {
                return ResourceManager.GetString("ZC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZQ.
        /// </summary>
        internal static string ZQ {
            get {
                return ResourceManager.GetString("ZQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZV.
        /// </summary>
        internal static string ZV {
            get {
                return ResourceManager.GetString("ZV", resourceCulture);
            }
        }
    }
}
